In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mssou\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mssou\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mssou\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mssou\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mssou\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mssou\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [14]:
#creating a data set
import pandas as pd

IshaProg={ "ProgName":["IE","BSP","Soonya","Samyama"],"Cost":[3000,6000,6000,0],"Duration":[7,3.5,4,8]}
IshaProgDataset=pd.DataFrame(IshaProg)
IshaProgDataset

  ProgName  Cost  Duration
0       IE  3000       7.0
1      BSP  6000       3.5
2   Soonya  6000       4.0
3  Samyama     0       8.0

In [15]:
indices = IshaProgDataset.index[IshaProgDataset['ProgName'] == 'IE']
#indicesList= IshaProgDataset.index[IshaProgDataset['ProgName'] == 'IE'or IshaProgDataset['ProgName'] =='BSP' ].tolist()

indicesList

[0]

In [16]:
IshaProgDataset.iloc[1,0]

'BSP'

In [17]:
IshaProgDataset.iloc[:]

  ProgName  Cost  Duration
0       IE  3000       7.0
1      BSP  6000       3.5
2   Soonya  6000       4.0
3  Samyama     0       8.0

In [23]:
#select programs with cost>0
ProgramWithCost= IshaProgDataset[IshaProgDataset[Cost

    Name  Age      City
0  Alice   25  New York
3  David   40  New York

In [4]:
import pandas as pd

# raeding from CSV files
dfIn = pd.read_csv('C:\\Users\\mssou\\pythonfiles\\TextFiles\\industry.csv')
print(dfIn.head(3))
print(dfIn.tail(7))

                       Industry  Funds Location
0            Accounting/Finance  10000        A
1  Advertising/Public Relations  20000        A
2            Aerospace/Aviation  20000        A
                    Industry  Funds Location
36                     Sales  30000        C
37          Science/Research  30000        C
38             Skilled Labor  30000        C
39                Technology  30000        C
40        Telecommunications  30000        C
41  Transportation/Logistics  30000        C
42                     Other  40000        C

In [6]:
#merge of two csv files
dfLc= pd.read_csv('C:\\Users\\mssou\\pythonfiles\\TextFiles\\Location.csv')
mergeddf= pd.merge(dfIn, dfLc, on='Location')
print(mergeddf)

                         Industry  Funds Location Countries  Customers
0              Accounting/Finance  10000        A   America         10
1    Advertising/Public Relations  20000        A   America         10
2              Aerospace/Aviation  20000        A   America         10
3   Arts/Entertainment/Publishing  20000        A   America         10
4                      Automotive  10000        A   America         10
5                Banking/Mortgage  10000        A   America         10
6            Business Development  10000        A   America         10
7            Business Opportunity  10000        A   America         10
8         Clerical/Administrative  10000        A   America         10
9         Construction/Facilities  10000        A   America         10
10                 Consumer Goods  10000        A   America         10
11               Customer Service  50000        A   America         10
12             Education/Training  50000        A   America         10
13               Energy/Utilities  50000        A   America         10
14                    Engineering  50000        A   America         10
15            Government/Military  50000        A   America         10
16                          Green  50000        B   Bharath        200
17                     Healthcare  50000        B   Bharath        200
18             Hospitality/Travel  50000        B   Bharath        200
19                Human Resources  50000        B   Bharath        200
20       Installation/Maintenance  50000        B   Bharath        200
21                      Insurance  50000        B   Bharath        200
22                       Internet  50000        B   Bharath        200
23                Job Search Aids  10000        B   Bharath        200
24       Law Enforcement/Security  10000        B   Bharath        200
25                          Legal  10000        B   Bharath        200
26           Management/Executive  10000        B   Bharath        200
27       Manufacturing/Operations  10000        B   Bharath        200
28                      Marketing  10000        B   Bharath        200
29           Non-Profit/Volunteer  30000        B   Bharath        200
30         Pharmaceutical/Biotech  30000        B   Bharath        200
31          Professional Services  30000        B   Bharath        200
32             QA/Quality Control  30000        C     China        100
33                    Real Estate  30000        C     China        100
34        Restaurant/Food Service  30000        C     China        100
35                         Retail  30000        C     China        100
36                          Sales  30000        C     China        100
37               Science/Research  30000        C     China        100
38                  Skilled Labor  30000        C     China        100
39                     Technology  30000        C     China        100
40             Telecommunications  30000        C     China        100
41       Transportation/Logistics  30000        C     China        100
42                          Other  40000        C     China        100

In [15]:
#Null values
dfIn2 = pd.read_csv('C:\\Users\\mssou\\pythonfiles\\TextFiles\\industry.csv')
print(dfIn2.isnull())

    Industry  Funds  Location
0      False  False     False
1      False   True     False
2      False   True     False
3      False  False     False
4      False  False     False
5      False  False     False
6      False  False     False
7      False  False     False
8      False  False     False
9      False  False     False
10     False  False     False
11     False  False     False
12     False  False      True
13     False  False     False
14     False  False     False
15     False  False     False
16     False  False     False
17     False  False     False
18     False  False     False
19     False  False     False
20     False  False     False
21     False   True     False
22     False  False     False
23     False  False     False
24     False  False     False
25     False  False     False
26     False  False     False
27     False  False     False
28     False  False     False
29     False  False     False
30     False  False     False
31     False  False     False
32     False  False     False
33     False  False     False
34     False  False     False
35     False  False      True
36     False  False     False
37     False  False     False
38     False  False     False
39     False  False     False
40     False  False     False
41     False  False     False
42     False  False     False